spring:
  application:
    name: Graduation Blog

# Swagger 属性配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  version: 1.0
  description: springfox swagger 3.0 Demo
  try-host: http://localhost:${server.port}