# 服务端口
server:
  port: 8082

# spring 基础配置
spring:
  # 数据源相关属性 - MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.100:3306/blog?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # elasticsearch 配置
  #  data:
  #    elasticsearch:
  #      repositories:
  #        enabled: true
  #  elasticsearch:
  #    rest:
  #      uris: http://localhost:9200

  # 视图前后缀
  mvc:
    view:
      prefix: /
      suffix: .html
    # 静态文件访问地址
    static-path-pattern: /**

  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/

# Swagger 属性配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  version: 1.0
  description: springfox swagger 3.0 Demo
  try-host: http://localhost:${server.port}

# 配置jwt相关属性
jwt:
  # header中的认证属性
  tokenHeader: Authorization
  # token的前缀，中间有个空格[Head token]
  tokenHead: Head
  # 加密密钥
  secret: test_secret
  # 过期时间，单位秒
  expire: 3600

# mybatis-plus配置
mybatis-plus:
  type-enums-package: com.whoai.blog.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
